name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: comchangs/action-yarn@v0.1-beta
    - name: Install dependencies
      run: yarn install
    - name: Build Core
      run: yarn build:core
