name: Run Tests

on:
  push:
    branches:
      - develop
    paths:
      - '**.html'
      - '**.js'
      - '**.json'
      - '**.css'
      - '**/test.yml'
      - '!dist/engine/core/**'
  pull_request:
    branches:
      - develop
    paths:
      - '**.html'
      - '**.js'
      - '**.json'
      - '**.css'
      - '!dist/engine/core/**'

jobs:
  cypress-run:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          lint-html: yarn run lint:html
          lint-javascript: yarn run lint:js
          lint-css: yarn run lint:css
          build: yarn run build:core
